### ISSUE TITLE
Logo not found

### ISSUE THREAD

**Issue by vitor-ao** [hexonet/whmcs-ispapi-widget-account#16]
The logo url now returns 404 (not found).
https://github.com/hexonet/whmcs-ispapi-widget-account/blob/5ae0c3050ebb488f65d8d870af64bfbbcd1f916d/ispapi_account.php#L161

**Comment by papakai** [comment]
Thanks for reporting. We moved from Travis CI to github actions and reviewed the folder structure of our modules while migrating. That's why this broke. Sorry for the inconveniences caused.
