### ISSUE TITLE
syntax error, unexpected '"'

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-widget-account#32]
I have no idea why this happens, but when we run cron.php with `do --DomainTransferSync`, we get this error:
```
[WHMCS Application] ERROR: ParseError: syntax error, unexpected '"', expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /home/username/public_html/client/modules/widgets/ispapi_account.php:126
```
Latest version of the widget :-)

**Comment by DennisSkov** [comment]
This could very likely be a local issue, it seems. There's no error when we run it using the full path to php `/opt/cpanel/ea-php74/root/usr/bin/php`. System default is also version 7.4, so I have no idea why one outputs an error when the other one doesn't.

**Comment by papakai** [comment]
Hey @DennisSkov,

Which Linux Distro are you exactly using?
Please provide the output of  `php --version`.

Basically this looks like an incompatibility of the HereDoc Syntax in use with your PHP Version. On my end just known for PHP < 7.4.  Changing the position of the closing heredoc tags to position/index 0 of its line may fix the issue for older releases. We also noticed that other distros than debian/ubuntu behave slightly differently in crons than in web server environment.

I am unsure if your php version in cron env is really php 7.4, but I could be wrong.

Sorry for the late reply, I will be back from holiday on Tuesday next week.

HTH already, keep me posted.

Kai

**Comment by papakai** [comment]
Can you please check this article regarding my hint that your cron environment could be using a different php version?
https://www.inmotionhosting.com/support/website/force-cron-jobs-php-version/

**Comment by DennisSkov** [comment]
Hey!

We're using CloudLinux 7. The issue was caused by a configuration issue, sorry for wasting your time.
In WHM, the default PHP version was configured to 7.4, but running `php -v` from the commandline would output version 7.2.
A restart of cPanel fixed the issue.

**Comment by papakai** [comment]
No Problem @DennisSkov, I was already sure that this can't be an issue on our end :-) You're always welcome.
